let TopStoriesSection:
  | 'arts'
  | 'automobiles'
  | 'books'
  | 'business'
  | 'food'
  | 'health'
  | 'home'
  | 'insider'
  | 'magazine'
  | 'movies'
  | 'opinion'
  | 'politics'
  | 'science'
  | 'sports'
  | 'technology'
  | 'travel'
  | 'upshot'
  | 'us'
  | 'world'

export type TopStoriesSection = typeof TopStoriesSection